# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mensagem.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'mensagem.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emensagem.proto\"!\n\x11\x45nviarDadosParams\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"5\n\x11\x45nviarDadosResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x16\n\x14\x43onsultarDadosParams\"-\n\x14\x43onsultarDadosResult\x12\x15\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x04.Log\"2\n\x03Log\x12\r\n\x05\x65poch\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t2\x86\x01\n\rClientService\x12\x35\n\x0b\x45nviarDados\x12\x12.EnviarDadosParams\x1a\x12.EnviarDadosResult\x12>\n\x0e\x43onsultarDados\x12\x15.ConsultarDadosParams\x1a\x15.ConsultarDadosResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mensagem_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVIARDADOSPARAMS']._serialized_start=18
  _globals['_ENVIARDADOSPARAMS']._serialized_end=51
  _globals['_ENVIARDADOSRESULT']._serialized_start=53
  _globals['_ENVIARDADOSRESULT']._serialized_end=106
  _globals['_CONSULTARDADOSPARAMS']._serialized_start=108
  _globals['_CONSULTARDADOSPARAMS']._serialized_end=130
  _globals['_CONSULTARDADOSRESULT']._serialized_start=132
  _globals['_CONSULTARDADOSRESULT']._serialized_end=177
  _globals['_LOG']._serialized_start=179
  _globals['_LOG']._serialized_end=229
  _globals['_CLIENTSERVICE']._serialized_start=232
  _globals['_CLIENTSERVICE']._serialized_end=366
# @@protoc_insertion_point(module_scope)
