# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mensagem_pb2 as mensagem__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mensagem_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnviarDados = channel.unary_unary(
                '/ClientService/EnviarDados',
                request_serializer=mensagem__pb2.EnviarDadosParams.SerializeToString,
                response_deserializer=mensagem__pb2.EnviarDadosResult.FromString,
                _registered_method=True)
        self.ConsultarDados = channel.unary_unary(
                '/ClientService/ConsultarDados',
                request_serializer=mensagem__pb2.ConsultarDadosParams.SerializeToString,
                response_deserializer=mensagem__pb2.ConsultarDadosResult.FromString,
                _registered_method=True)


class ClientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EnviarDados(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarDados(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnviarDados': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarDados,
                    request_deserializer=mensagem__pb2.EnviarDadosParams.FromString,
                    response_serializer=mensagem__pb2.EnviarDadosResult.SerializeToString,
            ),
            'ConsultarDados': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarDados,
                    request_deserializer=mensagem__pb2.ConsultarDadosParams.FromString,
                    response_serializer=mensagem__pb2.ConsultarDadosResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnviarDados(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ClientService/EnviarDados',
            mensagem__pb2.EnviarDadosParams.SerializeToString,
            mensagem__pb2.EnviarDadosResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarDados(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ClientService/ConsultarDados',
            mensagem__pb2.ConsultarDadosParams.SerializeToString,
            mensagem__pb2.ConsultarDadosResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReplicaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReplicarDados = channel.unary_unary(
                '/ReplicaService/ReplicarDados',
                request_serializer=mensagem__pb2.Log.SerializeToString,
                response_deserializer=mensagem__pb2.Ack.FromString,
                _registered_method=True)
        self.CommitarDados = channel.unary_unary(
                '/ReplicaService/CommitarDados',
                request_serializer=mensagem__pb2.CommitParams.SerializeToString,
                response_deserializer=mensagem__pb2.Ack.FromString,
                _registered_method=True)


class ReplicaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReplicarDados(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitarDados(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReplicarDados': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicarDados,
                    request_deserializer=mensagem__pb2.Log.FromString,
                    response_serializer=mensagem__pb2.Ack.SerializeToString,
            ),
            'CommitarDados': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitarDados,
                    request_deserializer=mensagem__pb2.CommitParams.FromString,
                    response_serializer=mensagem__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ReplicaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ReplicaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplicaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReplicarDados(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReplicaService/ReplicarDados',
            mensagem__pb2.Log.SerializeToString,
            mensagem__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitarDados(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReplicaService/CommitarDados',
            mensagem__pb2.CommitParams.SerializeToString,
            mensagem__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
